---
# vars file for roles/apache
sites_available: "/etc/apache2/sites-available"
sites_enabled: "{{ sites_available | replace('available', 'enabled') }}"
nossl_config_file: "wordpress.conf"
apache_http_config: "{{ sites_available }}/{{ nossl_config_file }}"
apache_ssl_path: /etc/apache2/ssl
key_file: "{{ apache_ssl_path }}/{{ fqdn }}.key"
csr_file: "{{ apache_ssl_path }}/{{ fqdn }}.csr"
crt_file: "{{ apache_ssl_path }}/{{ fqdn }}.crt"
ssl_config: "{{ sites_available }}/{{ fqdn }}-ssl.conf"
