---
# vars file for roles/apache
apache_base: "/etc/apache2"
sites_available: "{{ apache_base }}/sites-available"
sites_enabled: "{{ apache_base }}/sites-enabled"
conf_available: "{{ apache_base }}/conf-available"
conf_enabled: "{{ apache_base }}/conf-enabled"
ssl_config: "{{ sites_available }}/{{ fqdn }}-ssl.conf"
letsencrypt_certs_base: "/etc/letsencrypt/live"
letsencrypt_cert: "{{ letsencrypt_certs_base }}/{{ fqdn }}/fullchain.pem"
letsencrypt_key: "{{ letsencrypt_certs_base }}/{{ fqdn }}/privkey.pem"
