---
# tasks file for roles/apache

- name: install stuff
  apt:
    name:
      - apache2
    state: present
    update_cache: true
  notify: restart apache2


- name: get rid of default apache config
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: Create apache config
  template:
    src: "{{ nossl_config_file }}.j2"
    dest: "{{ apache_http_config }}"
  notify: restart apache2

- name: activate apache config
  file:
    src: "{{ apache_http_config }}"
    dest: "{{ sites_enabled }}/{{ nossl_config_file }}"
    state: link
  notify: restart apache2

- name: Enable mod rewrite
  apache2_module:
    name: rewrite
    state: present
  notify: restart apache2

- name: Create SSL dir
  file:
    path: "{{ apache_ssl_path }}"
    owner: root
    group: root
    mode: "0700"
    state: directory

- name: Create key
  openssl_privatekey:
    path: "{{ key_file }}"
    size: 2048

- name: Create csr
  openssl_csr:
    path: "{{ csr_file }}"
    privatekey_path: "{{ key_file }}"
    common_name: "{{ fqdn }}"

- name: Sign cert
  openssl_certificate:
    provider: selfsigned
    path: "{{ crt_file }}"
    privatekey_path: "{{ key_file }}"
    csr_path: "{{ csr_file }}"

- name: Enable ssl_module
  apache2_module:
    name: ssl
    state: present
  notify: restart apache2

- name: Create SSL config
  template:
    src: przestrzen-dev.conf.j2
    dest: "{{ ssl_config }}"

- name: Enable SSL config
  file:
    src: "{{ ssl_config }}"
    dest: "{{ sites_enabled }}/{{ fqdn }}-ssl.conf"
    state: link
  notify: restart apache2
