---
# tasks file for roles/apache

- name: install stuff
  apt:
    name:
      - apache2
      - certbot
    state: present

- name: Enable mod rewrite
  apache2_module:
    name: rewrite
    state: present
  notify: restart apache2

- name: Enable ssl_module
  apache2_module:
    name: ssl
    state: present
  notify: restart apache2


- name: get rid of default apache config
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: check if certs exists
  stat:
    path: "{{ letsencrypt_cert }}"
  register: letsencrypt_certs

- name: Stop apache
  service:
    name: apache2
    state: stopped
  when: letsencrypt_certs.stat.exists == False

- name: Create letsencrypt cert
  shell: certbot certonly --standalone --non-interactive --agree-tos -m maciej.wawrzynczuk@gmail.com -d przestrzen-dev.lamamind.com
  args:
    creates: "{{ letsencrypt_cert }}"
  notify: restart apache2

- name: Start apache
  service:
    name: apache2
    state: started

- name: Copy SSL redirect config
  copy:
    src: rewrite.conf
    dest: "{{ conf_available }}/rewrite.conf"

- name: Enable SSL redirect
  file:
    src: "{{ conf_available }}/rewrite.conf"
    dest: "{{ conf_enabled }}/rewrite.conf"
    state: link
  notify: restart apache2

- name: Create SSL config
  template:
    src: przestrzen-dev.conf.j2
    dest: "{{ ssl_config }}"
  notify: restart apache2

- name: Enable SSL config
  file:
    src: "{{ ssl_config }}"
    dest: "{{ sites_enabled }}/{{ fqdn }}-ssl.conf"
    state: link
  notify: restart apache2

