---
- hosts: all
  become: yes
  vars:
    db_name: "wordpress"
    db_user: "wordpress"
    db_password: fTR[x}?t+0ioVo"fg;/WH<-VFwM[@W2p
    wp_dir: /var/www/wordpress
  roles:
    - db
    - wp
    - apache
