---
- hosts: all
  become: yes
  vars:
    mariadb_socket: "/var/run/mysqld/mysqld.sock"
    db_name: "wordpress"
    db_user: "wordpress"
    db_password: "Zupa"     # Change me
    apache_http_config: /etc/apache2/sites-available/wordpress.conf
  roles:
    - db
    - wp
    - apache
