---
- hosts: all
  become: yes
  vars:
    db_name: "wordpress"
    db_user: "wordpress"
    db_password: "Zupa"     # Change me
    wp_dir: /var/www/wordpress
  roles:
    - db
    - wp
    - apache
